import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Julee&family=Just+Another+Hand&family=Kaushan+Script&family=Nothing+You+Could+Do&family=Roboto:ital,wght@0,100..900;1,100..900&family=Seaweed+Script&family=Vujahday+Script&display=swap');
        </style>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
